Web_books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('catalog.urls'))
]

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('author/', views.AuthorListView.as_view(), name='authors'),
    path('books/<slug:slug>/', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),

]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите жанр книги",
                            verbose_name="Жанр книги")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите язык книги',
                            verbose_name='Язык книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Имя автора",
                                  verbose_name='Имя автора')
    last_name = models.CharField(max_length=100,
                                 help_text="Фамилия автора",
                                 verbose_name='Фамилия автора')
    date_of_birth = models.DateField(help_text='Дата рождения',
                                     verbose_name='Дата рождения',
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text='Дата смерти',
                                     verbose_name='Дата смерти',
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(
        max_length=200,
        help_text='Введите название книги',
        verbose_name='Название книги'
    )
    slug = models.SlugField(max_length=200, unique=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE,
                              help_text='Выберите жанр книги', verbose_name='Жанр книги', null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE,
                                 help_text='Выберите язык книги', verbose_name='язык книги', null=True)
    author = models.ManyToManyField(Author, help_text='Выборите автор книги',
                                    verbose_name='автор книги', null=True)
    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание", verbose_name='Аннотация книги')
    isbn = models.CharField(max_length=13, help_text="Должно содержать 13 символов",
                            verbose_name="ISBN книги")

    def __str__(self):
        return self.title

    def display_author(self):
        """Строковое представление"""
        return ', '.join([author.last_name for author in self.author.all()])

    display_author.short_description = 'Авторы'

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'slug': self.slug})


class Status(models.Model):
    name = models.CharField(max_length=20, help_text="Должно содержать 13 символов", verbose_name="ISBN книги")

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text="Введите инвентарный номер экземпляра",
                               verbose_name="Инвентарный номер")
    imprint = models.CharField(max_length=200,
                               help_text="Введите издательство и год выnуска",
                               verbose_name="Издательство")
    status = models.ForeignKey(Status, on_delete=models.CASCADE,
                               null=True,
                               help_text='Изменить состояние экземпляра',
                               verbose_name="Cтaтyc экземпляра книги")
    due_back = models.DateField(null=True, blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дaтa окончания статуса")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True,
                                 verbose_name="Заказчик",
                                 help_text="Выберите заказчика книги")

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

catalog/views.py
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status=2).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits
    }
    return render(request, 'index.html', context)


class BookListView(ListView):
    model = Book
    paginate_by = 1


class BookDetailView(DetailView):
    model = Book
    slug_field = 'slug'


class AuthorListView(ListView):
    model = Author
    paginate_by = 1


class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user).filter(status__exact='2').order_by('due_back')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% block title %}<title>Миp книг </title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
        initial-scale=l">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/
        bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/
        jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/
        js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block head %}
    <img src="{% static 'images/logo.jpg' %}"
         style="width:100px; height:100px;" align="absmiddle">
    <font size=7 color="blue">Сайт "Мир книг"</font>
    {% endblock %}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Главная страница</a></li>
                <li><a href="{% url 'books' %}">Bce книги</a></li>
                <li><a href="{% url 'authors' %}">Bce авторы</a></li>
                {% if user.is_authenticated %}
                <li>Пользователь: {{ user.get_username }}</li>
                <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
                {% endif %}
            </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}
            {% block paginator %}
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                    <a href="{{request.path}}?page={{page_obj.previous_page_number }}">Предыдущий</a>
                    {% endif %}
                <span class="page-current"> Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
    {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{page_obj.next_page_number }}">Следующая</a>
    {% endif %}
    </span>
            </div>
            {% endif%}
            {% endblock paginator %}
            {% block footer %}
            {% block copyright %}
            <p>Copyright ООО "Люди и книги", 2020. Все права защищены</p>
            {% endblock %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/catalog/author_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Список авторов в БД: </h1>
{% if author_list %}
{% for author in author_list %}
<p>{{ author.first_name }} {{author.last_name}},
    <strong>Родился-</strong>{{author.date_of_birth}},
    <strong>Умер-</strong>{{author.date_of_death}}</p>
{% endfor %}
{% else %}
<p>В базе данных нет авторов</p>
{% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Название книги: {{ book.title }}</h1>
<p><strong>Жанр: </strong>{{book.genre}}</p>
<p><strong>Аннотация: </strong>{{book.summary}}</p>
<p><strong>ISBN: </strong>{{book.isbn}}</p>
<p><strong>Язык: </strong>{{book.language}}</p>
{% for author in book.author.all %}
<p><strong>Автор:</strong>
    <a href="{%url 'authors' %}">
        {{author.first_name}}
        {{author.last_name}}
    </a></p>
{% endfor %}
<div style="margin-left:20px;margin-top:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for сору in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 1 %} text-success
    {% elif copy.status == 2 %} text-danger
    {% else %} text-warning
    {% endif %}"> {{ сору.status }}</p>
    <p><strong>Издaтeльcтвo:</strong> {{сору.imprint}}</p>
    <p class="text-muted"><strong>Инвeнтapный нoмep:</strong> {{сору.inv_nom}}</p>
    <p><strong>Cтaтyc экземпляра книги в БД:</strong> {{ сору.status }}</p>
    {% endfor %}
</div>
{% endblock %}
<p><strong>Aвтop:</strong>
    <a href="{% url 'authors' %}">{{ author.firs_name }}  {{author.last_name}}</a>
</p>

templates/catalog/book_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Список книг в БД </h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{book.get_absolute_url}}">{{ book.title }}</a>
        {{book.genre}}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>В базе данных нет книг</p>
{% endif %}
{% endblock %}

templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}
{% block content %}
<h1>Взятые книги</h1>
{% if bookinstance_list %}
<ul>
    {% for bookinst in bookinstance_list %}
    <li class="(% if bookinst.is_overdue %}
text-danger(% endif %}">
        <a href="(% url 'book-detail' bookinst.book.pk %}">
            {{bookinst.book.title}}</a>
        ({{ bookinst.due back }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Нет книг со статусом В ЗАКАЗЕ.</p>
{% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{%block head %} {%endblock%}
{% block content %}
<h1>Главная старница</h1>

<p>Добро пожаловать в <em>Мир книг</em> , Это очень простой веб сайт, написанный на Джанго.
    Разработан на Пайтон в качестве примера с использованием Пайчарм</p>
<h2>Динамический контент</h2>

<p>База данных сайта Мир книг содержит следующее количество записей :</p>
<ul>
    <li><strong>Количество книг: </strong> {{num_books}}</li>
    <li><strong>Количество экземпляров книг: </strong> {{num_instances}}</li>
    <li><strong>Количество экзепляров книг в заказе: </strong> {{num_instances_available}}</li>
    <li><strong>Количество авторов книг: </strong> {{num_authors}}</li>
</ul>
<p>Количество посещений данной страницы - {{num_visits}}</p>
{% endblock content %}